---
name: _test
run-name: Test & Format & Pack

on:
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get pinned .NET version
        id: dotnet-version
        run: echo "value=$(cat global.json | jq -r '.sdk.version')" >> $GITHUB_OUTPUT

      - name: Setup dotnet
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a  # v3.0.3
        with:
          dotnet-version: ${{ steps.dotnet-version.outputs.value }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Checkout Repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0

      - name: Check format
        run: dotnet format --verify-no-changes

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --verbosity minimal

      - name: Test with the dotnet CLI
        run: dotnet test --no-build --logger "trx;LogFileName=pw-test-results.trx"

      - name: Report test results
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226  # v1.6.0
        if: always()
        with:
          name: Test Results
          path: "**/*-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true